language: go

script:
  - make test

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/gorilla/websocket
  - go get github.com/a8m/expect
