// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package server_test

type mockConn struct {
	WriteMessageCalled chan bool
	WriteMessageInput  struct {
		MsgType chan int
		Data    chan []byte
	}
	WriteMessageOutput struct {
		Ret0 chan error
	}
	ReadMessageCalled chan bool
	ReadMessageOutput struct {
		Ret0 chan int
		Ret1 chan []byte
		Ret2 chan error
	}
}

func newMockConn() *mockConn {
	m := &mockConn{}
	m.WriteMessageCalled = make(chan bool, 100)
	m.WriteMessageInput.MsgType = make(chan int, 100)
	m.WriteMessageInput.Data = make(chan []byte, 100)
	m.WriteMessageOutput.Ret0 = make(chan error, 100)
	m.ReadMessageCalled = make(chan bool, 100)
	m.ReadMessageOutput.Ret0 = make(chan int, 100)
	m.ReadMessageOutput.Ret1 = make(chan []byte, 100)
	m.ReadMessageOutput.Ret2 = make(chan error, 100)
	return m
}
func (m *mockConn) WriteMessage(msgType int, data []byte) error {
	m.WriteMessageCalled <- true
	m.WriteMessageInput.MsgType <- msgType
	m.WriteMessageInput.Data <- data
	return <-m.WriteMessageOutput.Ret0
}
func (m *mockConn) ReadMessage() (int, []byte, error) {
	m.ReadMessageCalled <- true
	return <-m.ReadMessageOutput.Ret0, <-m.ReadMessageOutput.Ret1, <-m.ReadMessageOutput.Ret2
}
